# Generated by Django 4.1 on 2022-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_address_alter_profile_credit_card_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='credit_card_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='credit_card_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
