# Generated by Django 4.1 on 2022-08-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_profile_address_remove_profile_credit_card_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_picture', models.ImageField(blank=True, null=True, upload_to='destinations')),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination_picture',
        ),
    ]
