# Generated by Django 4.1 on 2022-08-29 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_flightimage_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightimage',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flightimage'),
        ),
    ]
